/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author kontol 123
 */
public class makan extends javax.swing.JFrame {
    private int a, b, c;

    /**
     * Creates new form makan
     */
    public makan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sawi = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsawi = new javax.swing.JTextField();
        sop = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsop = new javax.swing.JTextField();
        rawon = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtrawon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ayam = new javax.swing.JCheckBox();
        telur = new javax.swing.JCheckBox();
        perkedel = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtayam = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        indomie = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtmie = new javax.swing.JTextField();
        txtnasgor = new javax.swing.JTextField();
        nasgor = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        es = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jeruk = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        teh = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        kopi = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtes = new javax.swing.JTextField();
        txtjeruk = new javax.swing.JTextField();
        txtteh = new javax.swing.JTextField();
        txtkopi = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        kembalian = new javax.swing.JToggleButton();
        hapus = new javax.swing.JToggleButton();
        totalharga = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        hitung = new javax.swing.JToggleButton();
        jTextField16 = new javax.swing.JTextField();
        txttelur = new javax.swing.JTextField();
        txtper = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 47, 52));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Freestyle Script", 1, 75)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BayarYuk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Warung Makan Mahasiswa");

        jLabel2.setText("Sayuran");

        sawi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sawiActionPerformed(evt);
            }
        });

        jLabel4.setText("Sayur Sawi Bening");

        jLabel5.setText("Rp 4000/prs");

        jLabel6.setText("Jumlah");

        txtsawi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsawiActionPerformed(evt);
            }
        });

        sop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sopActionPerformed(evt);
            }
        });

        jLabel7.setText("Sayur Sop");

        jLabel8.setText("Rp 3500/prs");

        txtsop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsopActionPerformed(evt);
            }
        });

        rawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawonActionPerformed(evt);
            }
        });

        jLabel9.setText("Sayur Rawon");

        jLabel10.setText("Rp 6000/prs");

        txtrawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrawonActionPerformed(evt);
            }
        });

        jLabel11.setText("Lauk Pauk");

        ayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamActionPerformed(evt);
            }
        });

        telur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telurActionPerformed(evt);
            }
        });

        perkedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkedelActionPerformed(evt);
            }
        });

        jLabel12.setText("Ayam Goreng");

        jLabel13.setText("Telur Dadar");

        jLabel14.setText("Perkedel");

        jLabel15.setText("Rp 7000/ptg");

        jLabel16.setText("Rp 3000/prs");

        jLabel17.setText("Rp 2000/prs");

        jLabel18.setText("Jumlah");

        txtayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtayamActionPerformed(evt);
            }
        });

        jLabel19.setText("Paket Hemat");

        indomie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indomieActionPerformed(evt);
            }
        });

        jLabel20.setText("Indomie+telur+teh es");

        jLabel21.setText("Rp 12000/prs");

        jLabel22.setText("Jumlah");

        txtmie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmieActionPerformed(evt);
            }
        });

        txtnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnasgorActionPerformed(evt);
            }
        });

        nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasgorActionPerformed(evt);
            }
        });

        jLabel23.setText("Nasi Goreng+teh es");

        jLabel24.setText("Rp 15000/prs");

        jLabel25.setText("Minuman");

        es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esActionPerformed(evt);
            }
        });

        jLabel26.setText("Es Teh");

        jeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jerukActionPerformed(evt);
            }
        });

        jLabel27.setText("Es Jeruk");

        teh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehActionPerformed(evt);
            }
        });

        jLabel28.setText("Teh Panas");

        kopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopiActionPerformed(evt);
            }
        });

        jLabel29.setText("Kopi");

        jLabel30.setText("Rp 3000/gls");

        jLabel31.setText("Rp 5000/gls");

        jLabel32.setText("Rp 2000/gls");

        jLabel33.setText("Rp 5000/gls");

        txtes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtesActionPerformed(evt);
            }
        });

        txtjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjerukActionPerformed(evt);
            }
        });

        txtteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttehActionPerformed(evt);
            }
        });

        txtkopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkopiActionPerformed(evt);
            }
        });

        jLabel34.setText("Jumlah");

        kembalian.setText("Kembalian");
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        totalharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalhargaMouseClicked(evt);
            }
        });

        jLabel35.setText("Bayar");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        txttelur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelurActionPerformed(evt);
            }
        });

        txtper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sawi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sop)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rawon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtsawi)
                            .addComponent(txtsop, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtrawon, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ayam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(telur)
                                            .addComponent(perkedel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(es)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel26))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(kopi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel29))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jeruk)
                                                    .addComponent(teh, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel28)))
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel17))))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtayam, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtes)
                                    .addComponent(txtjeruk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtteh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkopi)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttelur, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtper, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addGap(73, 73, 73))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(177, 177, 177)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(indomie)
                                    .addComponent(nasgor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jLabel21))
                                    .addComponent(jLabel20))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnasgor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(340, 340, 340))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bayar))
                            .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hapus)))
                        .addGap(18, 18, 18)
                        .addComponent(kembalian)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField16)
                        .addGap(188, 188, 188))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sawi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ayam)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(txtsawi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel13))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtsop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sop)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addComponent(txtrawon))
                                    .addComponent(rawon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel25)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(telur)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(perkedel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel34))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txttelur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indomie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(txtmie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel30)
                                .addComponent(txtes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 82, Short.MAX_VALUE)
                        .addComponent(es)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24)
                                    .addComponent(txtnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nasgor)))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapus)
                            .addComponent(hitung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembalian)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txtjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel28)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jeruk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teh)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kopi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sawiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sawiActionPerformed
        // TODO add your handling code here:
         if(sawi.isSelected()==true){
        txtsawi.setEditable(true);
        }else{txtsawi.setEditable(false);
        txtsawi.setText("");}
    }//GEN-LAST:event_sawiActionPerformed

    private void txtsawiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsawiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsawiActionPerformed

    private void sopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sopActionPerformed
        // TODO add your handling code here:
         if(sop.isSelected()==true){
        txtsop.setEditable(true);
        }else{txtsop.setEditable(false);
        txtsop.setText("");}
    }//GEN-LAST:event_sopActionPerformed

    private void txtsopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsopActionPerformed

    private void rawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawonActionPerformed
        // TODO add your handling code here:
         if(rawon.isSelected()==true){
        txtrawon.setEditable(true);
        }else{txtrawon.setEditable(false);
        txtrawon.setText("");}
    }//GEN-LAST:event_rawonActionPerformed

    private void txtrawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrawonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrawonActionPerformed

    private void perkedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkedelActionPerformed
        // TODO add your handling code here:
         if(perkedel.isSelected()==true){
        txtper.setEditable(true);
        }else{txtper.setEditable(false);
        txtper.setText("");}
    }//GEN-LAST:event_perkedelActionPerformed

    private void indomieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indomieActionPerformed
        // TODO add your handling code here:
         if(indomie.isSelected()==true){
        txtmie.setEditable(true);
        }else{txtmie.setEditable(false);
        txtmie.setText("");}
    }//GEN-LAST:event_indomieActionPerformed

    private void txtmieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmieActionPerformed

    private void txtnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnasgorActionPerformed

    private void nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasgorActionPerformed
        // TODO add your handling code here:
         if(nasgor.isSelected()==true){
        txtnasgor.setEditable(true);
        }else{txtnasgor.setEditable(false);
        txtnasgor.setText("");}
    }//GEN-LAST:event_nasgorActionPerformed

    private void txtesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtesActionPerformed

    private void txtjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjerukActionPerformed

    private void txttehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttehActionPerformed

    private void txtkopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkopiActionPerformed

    private void ayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamActionPerformed
        // TODO add your handling code here:
         if(ayam.isSelected()==true){
        txtayam.setEditable(true);
        }else{txtayam.setEditable(false);
        txtayam.setText("");}
    }//GEN-LAST:event_ayamActionPerformed

    private void telurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telurActionPerformed
        // TODO add your handling code here:
         if(telur.isSelected()==true){
        txttelur.setEditable(true);
        }else{txttelur.setEditable(false);
        txttelur.setText("");}
    }//GEN-LAST:event_telurActionPerformed

    private void esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esActionPerformed
        // TODO add your handling code here:
         if(es.isSelected()==true){
        txtes.setEditable(true);
        }else{txtes.setEditable(false);
        txtes.setText("");}
    }//GEN-LAST:event_esActionPerformed

    private void jerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jerukActionPerformed
        // TODO add your handling code here:
         if(jeruk.isSelected()==true){
        txtjeruk.setEditable(true);
        }else{txtjeruk.setEditable(false);
        txtjeruk.setText("");}
    }//GEN-LAST:event_jerukActionPerformed

    private void tehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehActionPerformed
        // TODO add your handling code here:
         if(teh.isSelected()==true){
        txtteh.setEditable(true);
        }else{txtteh.setEditable(false);
        txtteh.setText("");}
    }//GEN-LAST:event_tehActionPerformed

    private void kopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kopiActionPerformed
        // TODO add your handling code here:
         if(kopi.isSelected()==true){
        txtkopi.setEditable(true);
        }else{txtkopi.setEditable(false);
        txtkopi.setText("");}
    }//GEN-LAST:event_kopiActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int total =0;
        if (sawi.isSelected()){
            String sawi = txtsawi.getText();
            int txtsawi = Integer.parseInt(sawi);
            int hargasawi = txtsawi * 4000;
            total = total + hargasawi;       
        }  if (sop.isSelected()){
            String sop = txtsop.getText();
            int txtsop = Integer.parseInt(sop);
            int hargasop = txtsop * 3500;
            total = total + hargasop;
        } if (rawon.isSelected()){
            String rawon = txtrawon.getText();
            int txtrawon = Integer.parseInt(rawon);
            int hargarawon = txtrawon * 6000;
            total = total + hargarawon;
        }  if (ayam.isSelected()){
            String ayam = txtayam.getText();
            int txtayam = Integer.parseInt(ayam);
            int hargaayam = txtayam * 7000;
            total = total + hargaayam;
        }  if (telur.isSelected()){
            String telur = txttelur.getText();
            int txttelur = Integer.parseInt(telur);
            int hargatelur = txttelur * 2500;
            total = total + hargatelur;
        }  if(perkedel.isSelected()){
            String perkedel = txtper.getText();
            int txtper = Integer.parseInt(perkedel);
            int hargaperkedel = txtper * 6000;
            total = total + hargaperkedel;
        }  if(indomie.isSelected()){
            String indomie = txtmie.getText();
            int txtmie = Integer.parseInt(indomie);
            int hargaindomie = txtmie * 12000;
            total = total + hargaindomie;
        }  if(nasgor.isSelected()){
            String nasgor = txtnasgor.getText();
            int txtnasgor = Integer.parseInt(nasgor);
            int harganasgor = txtnasgor * 15000;
            total = total + harganasgor;
        }  if (es.isSelected()){
            String es = txtes.getText();
            int txtes = Integer.parseInt(es);
            int hargaes = txtes * 3000;
            total = total + hargaes;
        }  if (jeruk.isSelected()){
            String jeruk = txtjeruk.getText();
            int txtjeruk = Integer.parseInt(jeruk);
            int hargajeruk = txtjeruk * 5000;
            total = total + hargajeruk;
        }  if(kopi.isSelected()){
            String kopi = txtkopi.getText();
            int txtkopi = Integer.parseInt(kopi);
            int hargakopi = txtkopi * 5000;
            total = total + hargakopi;
        } 
        totalharga.setText("  "+total);
    }//GEN-LAST:event_hitungActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        txtsawi.setEditable(false);
        txtsawi.setText("");
        sawi.setSelected(false);
        
        txtayam.setText("");
        ayam.setSelected(false);
        
        txtes.setText("");
        es.setSelected(false);
        
        txtjeruk.setText("");
        jeruk.setSelected(false);
        
        txtkopi.setText("");
        kopi.setSelected(false);
        
        txtmie.setText("");
        indomie.setSelected(false);
        
        txtnasgor.setText("");
        nasgor.setSelected(false);
        
        txtper.setText("");
        perkedel.setSelected(false);
        
        txtrawon.setText("");
        rawon.setSelected(false);
        
        txtsop.setText("");
        sop.setSelected(false);
        
        txtteh.setText("");
        teh.setSelected(false);
        
        txttelur.setText("");
        telur.setSelected(false);
        
        totalharga.setText("");
        kembalian.setText("");
        bayar.setText("");
                
        
    }//GEN-LAST:event_hapusActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
        a = Integer.parseInt(bayar.getText());
        b = Integer.parseInt(totalharga.getText());
        c = (b - a);
        kembalian.setText(String.valueOf(c));
    }//GEN-LAST:event_kembalianActionPerformed

    private void totalhargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalhargaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaMouseClicked

    private void txtayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtayamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtayamActionPerformed

    private void txttelurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelurActionPerformed

    private void txtperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayam;
    private javax.swing.JTextField bayar;
    private javax.swing.JCheckBox es;
    private javax.swing.JToggleButton hapus;
    private javax.swing.JToggleButton hitung;
    private javax.swing.JCheckBox indomie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JCheckBox jeruk;
    private javax.swing.JToggleButton kembalian;
    private javax.swing.JCheckBox kopi;
    private javax.swing.JCheckBox nasgor;
    private javax.swing.JCheckBox perkedel;
    private javax.swing.JCheckBox rawon;
    private javax.swing.JCheckBox sawi;
    private javax.swing.JCheckBox sop;
    private javax.swing.JCheckBox teh;
    private javax.swing.JCheckBox telur;
    private javax.swing.JTextField totalharga;
    private javax.swing.JTextField txtayam;
    private javax.swing.JTextField txtes;
    private javax.swing.JTextField txtjeruk;
    private javax.swing.JTextField txtkopi;
    private javax.swing.JTextField txtmie;
    private javax.swing.JTextField txtnasgor;
    private javax.swing.JTextField txtper;
    private javax.swing.JTextField txtrawon;
    private javax.swing.JTextField txtsawi;
    private javax.swing.JTextField txtsop;
    private javax.swing.JTextField txtteh;
    private javax.swing.JTextField txttelur;
    // End of variables declaration//GEN-END:variables
}
